spring.datasource.url=jdbc:postgresql://143.47.185.120:9000/postgres
spring.datasource.username=postgres

spring.datasource.password=pwd

spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.=DEBUG
spring.application.name=kek