spring.datasource.url=jdbc:postgresql://localhost:9000/postgres
spring.datasource.username=postgres

spring.datasource.password=${MY_OPG_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver