spring.datasource.url=jdbc:postgresql://localhost:9000/bgs
spring.datasource.username=bgs_user

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=DEBUG

logging.level.org.trinogin.controller=DEBUG
logging.level.org.springframework.security=DEBUG

# Security
security.rememberme.key=${REMEMBER_ME_KEY:boardgamestat-remember-me-key}